import { dir } from 'i18next'
import i18nConfig from '../i18n/i18nConfig'

import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { Inter } from 'next/font/google'
import '@/app/globals.css'

import { ThemeProvider } from '@/components/providers/theme-provider'
import ModalProvider from '@/components/providers/modal-provider'
import TranslationsProvider from '@/components/providers/translation-provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'discord-clone',
  description: 'Generated by create next app'
}

export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }))
}

export default function RootLayout({ children, params }: { children: React.ReactNode; params: { locale: string } }) {
  return (
    <ClerkProvider>
      <html lang={params.locale} dir={dir(params.locale)}>
        <body className={inter.className}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <TranslationsProvider namespaces={['common']} locale={params.locale}>
              <ModalProvider />
              {children}
            </TranslationsProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
